from playwright.sync_api import  sync_playwright
import re



with sync_playwright() as p:
    browser = p.chromium.launch(headless=False, args=["--start-maximized"])
    context = browser.new_context(no_viewport=True)
    page = context.new_page()
    page.goto("http://dev8.kuotian.cc/login")
    # page.get_by_role("textbox", name="请输入登录账号").click()
    page.get_by_role("textbox", name="请输入登录账号").fill("18888888888")
    # page.get_by_role("textbox", name="请输入登录账号").press("Tab")
    page.get_by_role("textbox", name="请输入登录密码").fill("Hqq123456")
    page.get_by_role("button", name="登 录").click()
    # page.get_by_role("textbox", name="业务中心").click()
    # page.locator("div").filter(has_text=re.compile(r"^业务中心$")).click()
    # page.get_by_text("货源管理").click()
    # page.get_by_role("button", name="发布货源").click()
    # # page.get_by_role("img", name="撮合业务").click()
    # page.locator("img").nth(3).click()
    # page.get_by_text("请选择货品").click()
    # page.get_by_text("钢铁").click()
    # page.get_by_role("textbox", name="请输入货物数量(预估)").fill("200")
    # # page.get_by_text("请选择发货方式").click()
    # page.get_by_text("请选择发货方式").nth(1).click()
    # page.get_by_text("指派司机").click()
    # # page.get_by_text("开始日期").click()
    # # page.get_by_text("7").click()
    # # page.get_by_text("8").click()
    # page.get_by_role("textbox", name="开始日期").click()
    # page.get_by_text("1").nth(5).click()
    # page.get_by_role("gridcell", name="31").nth(1).click()
    #
    # page.get_by_text("请选择提货单位").click()
    # page.get_by_text("建设路提货点").click()
    # page.get_by_text("请选择收货单位").click()
    # page.get_by_text("祥厚路").click()
    # page.get_by_role("checkbox", name="同意").check()
    # page.get_by_role("button", name="提 交").click()


    context.close()
    # page.locator("img").nth(2).click()
    # page.get_by_text("请选择货品").click()
    # page.get_by_text("油").click()
    # page.get_by_role("textbox", name="请输入货物数量(预估)").click()
    # page.get_by_role("textbox", name="请输入货物数量(预估)").fill("200")
    # page.locator("div").filter(has_text=re.compile(r"^请选择发货方式$")).nth(2).click()
    # page.get_by_role("option", name="司机").click()
    # page.get_by_text("请选择发货方式").nth(1).click()
    # page.get_by_text("指派司机").click()
    # page.get_by_role("textbox", name="开始日期").click()
    # page.get_by_text("1").nth(5).click()
    # page.get_by_role("gridcell", name="31").nth(1).click()
    # page.get_by_text("请选择提货单位").click()
    # page.get_by_text("建设路提货点").click()
    # page.get_by_text("请选择收货单位").click()
    # page.get_by_text("祥厚路").click()
    # page.get_by_role("checkbox", name="同意").check()
    # page.get_by_role("button", name="提 交").click()